services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-manage-fe
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - AUTH_TRUST_HOST=true
    env_file:
      - .env
