import { Doctor } from '@/types/doctor';

export const mockDoctors: Doctor[] = [
  {
    id: 1,
    name: 'Dr. Mick Thompson',
    specialty: 'Cardiologist',
    available: 'Mon, 20 Jan 2025',
    price: 499,
    image: '/images/doctor.png',
  },
  {
    id: 2,
    name: 'Dr. Sarah Johnson',
    specialty: 'Orthopedic Surgeon',
    available: 'Wed, 22 Jan 2025',
    price: 450,
    image: '/images/doctor.png',
  },
  {
    id: 3,
    name: 'Dr. Emily Carter',
    specialty: 'Pediatrician',
    available: 'Fri, 24 Jan 2025',
    price: 300,
    image: '/images/doctor.png',
  },
  {
    id: 4,
    name: 'Dr. Robert Miller',
    specialty: 'Dermatologist',
    available: 'Tue, 28 Jan 2025',
    price: 350,
    image: '/images/doctor.png',
  },
  {
    id: 5,
    name: 'Dr. Olivia Smith',
    specialty: 'Neurologist',
    available: 'Thu, 30 Jan 2025',
    price: 600,
    image: '/images/doctor.png',
  },
  {
    id: 6,
    name: 'Dr. James Anderson',
    specialty: 'Oncologist',
    available: 'Mon, 3 Feb 2025',
    price: 700,
    image: '/images/doctor.png',
  },
  {
    id: 7,
    name: 'Dr. Sophia Wilson',
    specialty: 'Gynecologist',
    available: 'Wed, 5 Feb 2025',
    price: 400,
    image: '/images/doctor.png',
  },
  {
    id: 8,
    name: 'Dr. William Taylor',
    specialty: 'Ophthalmologist',
    available: 'Fri, 7 Feb 2025',
    price: 380,
    image: '/images/doctor.png',
  },
  {
    id: 9,
    name: 'Dr. Isabella Davis',
    specialty: 'Dentist',
    available: 'Mon, 10 Feb 2025',
    price: 250,
    image: '/images/doctor.png',
  },
  {
    id: 10,
    name: 'Dr. Ethan Brown',
    specialty: 'ENT Specialist',
    available: 'Wed, 12 Feb 2025',
    price: 320,
    image: '/images/doctor.png',
  },
  {
    id: 11,
    name: 'Dr. Ava Martin',
    specialty: 'Psychiatrist',
    available: 'Fri, 14 Feb 2025',
    price: 550,
    image: '/images/doctor.png',
  },
  {
    id: 12,
    name: 'Dr. Lucas Thompson',
    specialty: 'Radiologist',
    available: 'Mon, 17 Feb 2025',
    price: 480,
    image: '/images/doctor.png',
  },
  {
    id: 13,
    name: 'Dr. Mia Harris',
    specialty: 'General Surgeon',
    available: 'Wed, 19 Feb 2025',
    price: 520,
    image: '/images/doctor.png',
  },
  {
    id: 14,
    name: 'Dr. Henry Moore',
    specialty: 'Urologist',
    available: 'Fri, 21 Feb 2025',
    price: 460,
    image: '/images/doctor.png',
  },
  {
    id: 15,
    name: 'Dr. Charlotte Clark',
    specialty: 'Endocrinologist',
    available: 'Mon, 24 Feb 2025',
    price: 500,
    image: '/images/doctor.png',
  },
  {
    id: 16,
    name: 'Dr. Benjamin Lewis',
    specialty: 'Pulmonologist',
    available: 'Wed, 26 Feb 2025',
    price: 430,
    image: '/images/doctor.png',
  },
  {
    id: 17,
    name: 'Dr. Amelia Walker',
    specialty: 'Rheumatologist',
    available: 'Fri, 28 Feb 2025',
    price: 410,
    image: '/images/doctor.png',
  },
  {
    id: 18,
    name: 'Dr. Daniel Young',
    specialty: 'Hematologist',
    available: 'Mon, 3 Mar 2025',
    price: 620,
    image: '/images/doctor.png',
  },
  {
    id: 19,
    name: 'Dr. Grace King',
    specialty: 'Gastroenterologist',
    available: 'Wed, 5 Mar 2025',
    price: 580,
    image: '/images/doctor.png',
  },
  {
    id: 20,
    name: 'Dr. Matthew Scott',
    specialty: 'Plastic Surgeon',
    available: 'Fri, 7 Mar 2025',
    price: 850,
    image: '/images/doctor.png',
  },
];
