import { Doctor } from '@/types/doctor';

export const mockDoctors: Doctor[] = [
  {
    id: 1,
    name: 'Dr. Mick Thompson',
    specialty: 'Cardiologist',
    available: 'Mon, 20 Jan 2025',
    price: 499,
    image: '/images/doctor.png',
  },
  {
    id: 2,
    name: 'Dr. Sarah Johnson',
    specialty: 'Orthopedic Surgeon',
    available: 'Wed, 22 Jan 2025',
    price: 450,
    image: '/images/doctor.png',
  },
  {
    id: 3,
    name: 'Dr. Emily Carter',
    specialty: 'Pediatrician',
    available: 'Fri, 24 Jan 2025',
    price: 300,
    image: '/images/doctor.png',
  },
  {
    id: 4,
    name: 'Dr. Robert Miller',
    specialty: 'Dermatologist',
    available: 'Tue, 28 Jan 2025',
    price: 350,
    image: '/images/doctor.png',
  },
  {
    id: 5,
    name: 'Dr. Olivia Smith',
    specialty: 'Neurologist',
    available: 'Thu, 30 Jan 2025',
    price: 600,
    image: '/images/doctor.png',
  },
  {
    id: 6,
    name: 'Dr. James Anderson',
    specialty: 'Oncologist',
    available: 'Mon, 3 Feb 2025',
    price: 700,
    image: '/images/doctor.png',
  },
  {
    id: 7,
    name: 'Dr. Sophia Wilson',
    specialty: 'Gynecologist',
    available: 'Wed, 5 Feb 2025',
    price: 400,
    image: '/images/doctor.png',
  },
  {
    id: 8,
    name: 'Dr. William Taylor',
    specialty: 'Ophthalmologist',
    available: 'Fri, 7 Feb 2025',
    price: 380,
    image: '/images/doctor.png',
  },
  {
    id: 9,
    name: 'Dr. Isabella Davis',
    specialty: 'Dentist',
    available: 'Mon, 10 Feb 2025',
    price: 250,
    image: '/images/doctor.png',
  },
  {
    id: 10,
    name: 'Dr. Ethan Brown',
    specialty: 'ENT Specialist',
    available: 'Wed, 12 Feb 2025',
    price: 320,
    image: '/images/doctor.png',
  },
  {
    id: 11,
    name: 'Dr. Ava Martin',
    specialty: 'Psychiatrist',
    available: 'Fri, 14 Feb 2025',
    price: 550,
    image: '/images/doctor.png',
  },
  {
    id: 12,
    name: 'Dr. Lucas Thompson',
    specialty: 'Radiologist',
    available: 'Mon, 17 Feb 2025',
    price: 480,
    image: '/images/doctor.png',
  },
  {
    id: 13,
    name: 'Dr. Mia Harris',
    specialty: 'General Surgeon',
    available: 'Wed, 19 Feb 2025',
    price: 520,
    image: '/images/doctor.png',
  },
  {
    id: 14,
    name: 'Dr. Henry Moore',
    specialty: 'Urologist',
    available: 'Fri, 21 Feb 2025',
    price: 460,
    image: '/images/doctor.png',
  },
  {
    id: 15,
    name: 'Dr. Charlotte Clark',
    specialty: 'Endocrinologist',
    available: 'Mon, 24 Feb 2025',
    price: 500,
    image: '/images/doctor.png',
  },
  {
    id: 16,
    name: 'Dr. Benjamin Lewis',
    specialty: 'Pulmonologist',
    available: 'Wed, 26 Feb 2025',
    price: 430,
    image: '/images/doctor.png',
  },
  {
    id: 17,
    name: 'Dr. Amelia Walker',
    specialty: 'Rheumatologist',
    available: 'Fri, 28 Feb 2025',
    price: 410,
    image: '/images/doctor.png',
  },
  {
    id: 18,
    name: 'Dr. Daniel Young',
    specialty: 'Hematologist',
    available: 'Mon, 3 Mar 2025',
    price: 620,
    image: '/images/doctor.png',
  },
  {
    id: 19,
    name: 'Dr. Grace King',
    specialty: 'Gastroenterologist',
    available: 'Wed, 5 Mar 2025',
    price: 580,
    image: '/images/doctor.png',
  },
  {
    id: 20,
    name: 'Dr. Matthew Scott',
    specialty: 'Plastic Surgeon',
    available: 'Fri, 7 Mar 2025',
    price: 850,
    image: '/images/doctor.png',
  },
];

export const mockPatients = [
  {
    id: 1,
    name: 'Alberto Ripley',
    age: 26,
    gender: 'Male',
    lastAppointment: 'Mon, 30 Apr 2025',
    location: 'Green Square, New York, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 2,
    name: 'Susan Babin',
    age: 21,
    gender: 'Female',
    lastAppointment: 'Wed, 15 Apr 2025',
    location: 'Lakeview Drive, Chicago, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 3,
    name: 'Michael Chen',
    age: 34,
    gender: 'Male',
    lastAppointment: 'Tue, 25 Apr 2025',
    location: 'Downtown, Los Angeles, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 4,
    name: 'Sarah Johnson',
    age: 29,
    gender: 'Female',
    lastAppointment: 'Fri, 28 Apr 2025',
    location: 'River North, Boston, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 5,
    name: 'David Wilson',
    age: 45,
    gender: 'Male',
    lastAppointment: 'Mon, 22 Apr 2025',
    location: 'West End, Seattle, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 6,
    name: 'Emily Davis',
    age: 31,
    gender: 'Female',
    lastAppointment: 'Thu, 18 Apr 2025',
    location: 'Midtown, Atlanta, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 7,
    name: 'Robert Martinez',
    age: 52,
    gender: 'Male',
    lastAppointment: 'Wed, 24 Apr 2025',
    location: 'Uptown, Dallas, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 8,
    name: 'Jennifer Brown',
    age: 38,
    gender: 'Female',
    lastAppointment: 'Mon, 29 Apr 2025',
    location: 'South Side, Miami, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 9,
    name: 'Thomas Anderson',
    age: 41,
    gender: 'Male',
    lastAppointment: 'Tue, 16 Apr 2025',
    location: 'East Village, Denver, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 10,
    name: 'Lisa Taylor',
    age: 27,
    gender: 'Female',
    lastAppointment: 'Fri, 26 Apr 2025',
    location: 'North Park, Phoenix, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 11,
    name: 'Christopher Lee',
    age: 33,
    gender: 'Male',
    lastAppointment: 'Thu, 19 Apr 2025',
    location: 'Central District, San Francisco, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 12,
    name: 'Amanda White',
    age: 24,
    gender: 'Female',
    lastAppointment: 'Mon, 23 Apr 2025',
    location: 'Old Town, Portland, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 13,
    name: 'Kevin Garcia',
    age: 47,
    gender: 'Male',
    lastAppointment: 'Wed, 17 Apr 2025',
    location: 'The Loop, Detroit, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 14,
    name: 'Michelle Rodriguez',
    age: 35,
    gender: 'Female',
    lastAppointment: 'Tue, 30 Apr 2025',
    location: 'French Quarter, New Orleans, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 15,
    name: 'James Miller',
    age: 58,
    gender: 'Male',
    lastAppointment: 'Fri, 19 Apr 2025',
    location: 'Capitol Hill, Washington DC, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 16,
    name: 'Jessica Moore',
    age: 32,
    gender: 'Female',
    lastAppointment: 'Thu, 25 Apr 2025',
    location: 'Highland Park, Minneapolis, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 17,
    name: 'Daniel Jackson',
    age: 39,
    gender: 'Male',
    lastAppointment: 'Mon, 22 Apr 2025',
    location: 'Queen Anne, Baltimore, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 18,
    name: 'Stephanie Harris',
    age: 28,
    gender: 'Female',
    lastAppointment: 'Wed, 24 Apr 2025',
    location: 'Buckhead, Charlotte, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 19,
    name: 'Matthew Clark',
    age: 43,
    gender: 'Male',
    lastAppointment: 'Tue, 16 Apr 2025',
    location: 'University District, Austin, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 20,
    name: 'Rebecca Lewis',
    age: 30,
    gender: 'Female',
    lastAppointment: 'Fri, 26 Apr 2025',
    location: 'Historic District, Nashville, USA',
    avatar: '/images/doctor.png',
  },
];
