import { Doctor } from '@/types/doctor';

export const mockDoctors: Doctor[] = [
  {
    id: 1,
    name: 'Dr. Mick Thompson',
    specialty: 'Cardiologist',
    available: 'Mon, 20 Jan 2025',
    price: 499,
    image: '/images/doctor.png',
  },
  {
    id: 2,
    name: 'Dr. Sarah Johnson',
    specialty: 'Orthopedic Surgeon',
    available: 'Wed, 22 Jan 2025',
    price: 450,
    image: '/images/doctor.png',
  },
  {
    id: 3,
    name: 'Dr. Emily Carter',
    specialty: 'Pediatrician',
    available: 'Fri, 24 Jan 2025',
    price: 300,
    image: '/images/doctor.png',
  },
  {
    id: 4,
    name: 'Dr. Robert Miller',
    specialty: 'Dermatologist',
    available: 'Tue, 28 Jan 2025',
    price: 350,
    image: '/images/doctor.png',
  },
  {
    id: 5,
    name: 'Dr. Olivia Smith',
    specialty: 'Neurologist',
    available: 'Thu, 30 Jan 2025',
    price: 600,
    image: '/images/doctor.png',
  },
  {
    id: 6,
    name: 'Dr. James Anderson',
    specialty: 'Oncologist',
    available: 'Mon, 3 Feb 2025',
    price: 700,
    image: '/images/doctor.png',
  },
  {
    id: 7,
    name: 'Dr. Sophia Wilson',
    specialty: 'Gynecologist',
    available: 'Wed, 5 Feb 2025',
    price: 400,
    image: '/images/doctor.png',
  },
  {
    id: 8,
    name: 'Dr. William Taylor',
    specialty: 'Ophthalmologist',
    available: 'Fri, 7 Feb 2025',
    price: 380,
    image: '/images/doctor.png',
  },
  {
    id: 9,
    name: 'Dr. Isabella Davis',
    specialty: 'Dentist',
    available: 'Mon, 10 Feb 2025',
    price: 250,
    image: '/images/doctor.png',
  },
  {
    id: 10,
    name: 'Dr. Ethan Brown',
    specialty: 'ENT Specialist',
    available: 'Wed, 12 Feb 2025',
    price: 320,
    image: '/images/doctor.png',
  },
  {
    id: 11,
    name: 'Dr. Ava Martin',
    specialty: 'Psychiatrist',
    available: 'Fri, 14 Feb 2025',
    price: 550,
    image: '/images/doctor.png',
  },
  {
    id: 12,
    name: 'Dr. Lucas Thompson',
    specialty: 'Radiologist',
    available: 'Mon, 17 Feb 2025',
    price: 480,
    image: '/images/doctor.png',
  },
  {
    id: 13,
    name: 'Dr. Mia Harris',
    specialty: 'General Surgeon',
    available: 'Wed, 19 Feb 2025',
    price: 520,
    image: '/images/doctor.png',
  },
  {
    id: 14,
    name: 'Dr. Henry Moore',
    specialty: 'Urologist',
    available: 'Fri, 21 Feb 2025',
    price: 460,
    image: '/images/doctor.png',
  },
  {
    id: 15,
    name: 'Dr. Charlotte Clark',
    specialty: 'Endocrinologist',
    available: 'Mon, 24 Feb 2025',
    price: 500,
    image: '/images/doctor.png',
  },
  {
    id: 16,
    name: 'Dr. Benjamin Lewis',
    specialty: 'Pulmonologist',
    available: 'Wed, 26 Feb 2025',
    price: 430,
    image: '/images/doctor.png',
  },
  {
    id: 17,
    name: 'Dr. Amelia Walker',
    specialty: 'Rheumatologist',
    available: 'Fri, 28 Feb 2025',
    price: 410,
    image: '/images/doctor.png',
  },
  {
    id: 18,
    name: 'Dr. Daniel Young',
    specialty: 'Hematologist',
    available: 'Mon, 3 Mar 2025',
    price: 620,
    image: '/images/doctor.png',
  },
  {
    id: 19,
    name: 'Dr. Grace King',
    specialty: 'Gastroenterologist',
    available: 'Wed, 5 Mar 2025',
    price: 580,
    image: '/images/doctor.png',
  },
  {
    id: 20,
    name: 'Dr. Matthew Scott',
    specialty: 'Plastic Surgeon',
    available: 'Fri, 7 Mar 2025',
    price: 850,
    image: '/images/doctor.png',
  },
];

export const mockPatients = [
  {
    id: 1,
    name: 'Alberto Ripley',
    age: 26,
    gender: 'Male',
    lastAppointment: 'Mon, 30 Apr 2025',
    location: 'Green Square, New York, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 2,
    name: 'Susan Babin',
    age: 21,
    gender: 'Female',
    lastAppointment: 'Wed, 15 Apr 2025',
    location: 'Lakeview Drive, Chicago, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 3,
    name: 'Michael Chen',
    age: 34,
    gender: 'Male',
    lastAppointment: 'Tue, 25 Apr 2025',
    location: 'Downtown, Los Angeles, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 4,
    name: 'Sarah Johnson',
    age: 29,
    gender: 'Female',
    lastAppointment: 'Fri, 28 Apr 2025',
    location: 'River North, Boston, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 5,
    name: 'David Wilson',
    age: 45,
    gender: 'Male',
    lastAppointment: 'Mon, 22 Apr 2025',
    location: 'West End, Seattle, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 6,
    name: 'Emily Davis',
    age: 31,
    gender: 'Female',
    lastAppointment: 'Thu, 18 Apr 2025',
    location: 'Midtown, Atlanta, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 7,
    name: 'Robert Martinez',
    age: 52,
    gender: 'Male',
    lastAppointment: 'Wed, 24 Apr 2025',
    location: 'Uptown, Dallas, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 8,
    name: 'Jennifer Brown',
    age: 38,
    gender: 'Female',
    lastAppointment: 'Mon, 29 Apr 2025',
    location: 'South Side, Miami, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 9,
    name: 'Thomas Anderson',
    age: 41,
    gender: 'Male',
    lastAppointment: 'Tue, 16 Apr 2025',
    location: 'East Village, Denver, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 10,
    name: 'Lisa Taylor',
    age: 27,
    gender: 'Female',
    lastAppointment: 'Fri, 26 Apr 2025',
    location: 'North Park, Phoenix, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 11,
    name: 'Christopher Lee',
    age: 33,
    gender: 'Male',
    lastAppointment: 'Thu, 19 Apr 2025',
    location: 'Central District, San Francisco, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 12,
    name: 'Amanda White',
    age: 24,
    gender: 'Female',
    lastAppointment: 'Mon, 23 Apr 2025',
    location: 'Old Town, Portland, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 13,
    name: 'Kevin Garcia',
    age: 47,
    gender: 'Male',
    lastAppointment: 'Wed, 17 Apr 2025',
    location: 'The Loop, Detroit, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 14,
    name: 'Michelle Rodriguez',
    age: 35,
    gender: 'Female',
    lastAppointment: 'Tue, 30 Apr 2025',
    location: 'French Quarter, New Orleans, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 15,
    name: 'James Miller',
    age: 58,
    gender: 'Male',
    lastAppointment: 'Fri, 19 Apr 2025',
    location: 'Capitol Hill, Washington DC, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 16,
    name: 'Jessica Moore',
    age: 32,
    gender: 'Female',
    lastAppointment: 'Thu, 25 Apr 2025',
    location: 'Highland Park, Minneapolis, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 17,
    name: 'Daniel Jackson',
    age: 39,
    gender: 'Male',
    lastAppointment: 'Mon, 22 Apr 2025',
    location: 'Queen Anne, Baltimore, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 18,
    name: 'Stephanie Harris',
    age: 28,
    gender: 'Female',
    lastAppointment: 'Wed, 24 Apr 2025',
    location: 'Buckhead, Charlotte, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 19,
    name: 'Matthew Clark',
    age: 43,
    gender: 'Male',
    lastAppointment: 'Tue, 16 Apr 2025',
    location: 'University District, Austin, USA',
    avatar: '/images/doctor.png',
  },
  {
    id: 20,
    name: 'Rebecca Lewis',
    age: 30,
    gender: 'Female',
    lastAppointment: 'Fri, 26 Apr 2025',
    location: 'Historic District, Nashville, USA',
    avatar: '/images/doctor.png',
  },
];
// const/mock-data.ts
export const mockdataPatients = [
  {
    id: 1,
    name: 'Morished Ali',
    username: '@morished',
    sex: 'Male',
    age: 62,
    status: 'Finished',
    email: 'Morished.Ali@mail.com',
    phone: '+8807FB001022',
    bp: '120/90',
    pulse: '180 bpm',
    weight: '62 Kg',
    lastChecked: 'Dr. Pearly on 20 November 2022',
    prescription: '#201102020128',
    observation: 'High Fever and cough at normal.',
    testsWithPrescriptions: [
      {
        test: 'X-Ray',
        prescription: 'Cap.GALPOL 500mg 1 + 1 + 1 × 5 Days',
      },
      {
        test: 'Blood Test',
        prescription: 'Cap.DELCON 10mg 0 + 1 + 0 × 3 Days',
      },
      {
        test: 'Urine Test',
        prescription: 'Cap.LEVOLIN 500mg 1 + 1 + 1 × 5 Days',
      },
      {
        test: 'Endoscopy',
        prescription: 'Cap.ME-FTAL 10mg 0 + 1 + 0 × 3 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '5.5', unit: '1094/L' },
      { test: 'RBC', value: '12.5', unit: '1094/L' },
      { test: 'HGB', value: '136', unit: 'g/L' },
      { test: 'HCT', value: '12.5', unit: 'L/L' },
      { test: 'MCV', value: '12.5', unit: 'fL' },
    ],
    appointmentDate: '2024-01-15',
  },
  {
    id: 2,
    name: 'Demi Wilkinson',
    username: '@demi',
    sex: 'Male',
    age: 70,
    status: 'Finished',
    email: 'demi.wilkinson@mail.com',
    phone: '+8807FB001023',
    bp: '130/85',
    pulse: '72 bpm',
    weight: '75 Kg',
    lastChecked: 'Dr. Smith on 15 January 2024',
    prescription: '#201102020129',
    observation: 'Regular checkup, all parameters normal.',
    testsWithPrescriptions: [
      {
        test: 'Blood Test',
        prescription: 'Cap.ASPIRIN 100mg 0 + 0 + 1 × 30 Days',
      },
      {
        test: 'ECG',
        prescription: 'Tab.METFORMIN 500mg 1 + 0 + 1 × 90 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '6.2', unit: '1094/L' },
      { test: 'RBC', value: '4.8', unit: '1094/L' },
      { test: 'HGB', value: '14.2', unit: 'g/L' },
      { test: 'HCT', value: '42.5', unit: 'L/L' },
      { test: 'MCV', value: '88.5', unit: 'fL' },
    ],
    appointmentDate: '2024-01-15',
  },
  {
    id: 3,
    name: 'Ohka Rhye',
    username: '@ohka',
    sex: 'Female',
    age: 63,
    status: 'Waiting',
    email: 'ohka.rhye@mail.com',
    phone: '+8807FB001024',
    bp: '118/78',
    pulse: '68 bpm',
    weight: '58 Kg',
    lastChecked: 'Dr. Johnson on 10 January 2024',
    prescription: '#201102020130',
    observation: 'Mild headache and fatigue reported.',
    testsWithPrescriptions: [
      {
        test: 'MRI',
        prescription: 'Tab.PARACETAMOL 500mg 1 + 0 + 1 × 7 Days',
      },
      {
        test: 'Thyroid Test',
        prescription: 'Cap.VITAMIN-D 1000IU 0 + 0 + 1 × 60 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '7.1', unit: '1094/L' },
      { test: 'RBC', value: '4.5', unit: '1094/L' },
      { test: 'HGB', value: '13.8', unit: 'g/L' },
      { test: 'HCT', value: '40.2', unit: 'L/L' },
      { test: 'MCV', value: '89.0', unit: 'fL' },
    ],
    appointmentDate: '2024-01-16',
  },
  {
    id: 4,
    name: 'Phoenix Baker',
    username: '@phoenix',
    sex: 'Male',
    age: 39,
    status: 'Cancelled',
    email: 'phoenix.baker@mail.com',
    phone: '+8807FB001025',
    bp: '125/80',
    pulse: '75 bpm',
    weight: '82 Kg',
    lastChecked: 'Dr. Wilson on 08 January 2024',
    prescription: '#201102020131',
    observation: 'Sports injury follow-up required.',
    testsWithPrescriptions: [
      {
        test: 'X-Ray',
        prescription: 'Tab.IBUPROFEN 400mg 1 + 0 + 1 × 10 Days',
      },
      {
        test: 'Physical Therapy',
        prescription: 'Cap.MUSCLE-RELAX 10mg 0 + 1 + 0 × 14 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '8.2', unit: '1094/L' },
      { test: 'RBC', value: '5.1', unit: '1094/L' },
      { test: 'HGB', value: '15.0', unit: 'g/L' },
      { test: 'HCT', value: '45.0', unit: 'L/L' },
      { test: 'MCV', value: '88.0', unit: 'fL' },
    ],
    appointmentDate: '2024-01-16',
  },
  {
    id: 5,
    name: 'Lana Steiner',
    username: '@lana',
    sex: 'Female',
    age: 36,
    status: 'Cancelled',
    email: 'lana.steiner@mail.com',
    phone: '+8807FB001026',
    bp: '110/70',
    pulse: '65 bpm',
    weight: '55 Kg',
    lastChecked: 'Dr. Brown on 05 January 2024',
    prescription: '#201102020132',
    observation: 'Routine pregnancy checkup.',
    testsWithPrescriptions: [
      {
        test: 'Ultrasound',
        prescription: 'Tab.FOLIC-ACID 5mg 1 + 0 + 0 × 90 Days',
      },
      {
        test: 'Blood Test',
        prescription: 'Cap.PRENATAL-VIT 1 + 0 + 0 × 90 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '9.5', unit: '1094/L' },
      { test: 'RBC', value: '3.8', unit: '1094/L' },
      { test: 'HGB', value: '12.5', unit: 'g/L' },
      { test: 'HCT', value: '36.0', unit: 'L/L' },
      { test: 'MCV', value: '92.0', unit: 'fL' },
    ],
    appointmentDate: '2024-01-17',
  },
  {
    id: 6,
    name: 'Alex Chen',
    username: '@alex',
    sex: 'Male',
    age: 45,
    status: 'Finished',
    email: 'alex.chen@mail.com',
    phone: '+8807FB001027',
    bp: '135/88',
    pulse: '70 bpm',
    weight: '78 Kg',
    lastChecked: 'Dr. Davis on 12 January 2024',
    prescription: '#201102020133',
    observation: 'Diabetes management and monitoring.',
    testsWithPrescriptions: [
      {
        test: 'Blood Sugar',
        prescription: 'Tab.METFORMIN 850mg 1 + 0 + 1 × 30 Days',
      },
      {
        test: 'Cholesterol',
        prescription: 'Tab.ATORVASTATIN 20mg 0 + 0 + 1 × 30 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '6.8', unit: '1094/L' },
      { test: 'RBC', value: '4.9', unit: '1094/L' },
      { test: 'HGB', value: '14.8', unit: 'g/L' },
      { test: 'HCT', value: '43.5', unit: 'L/L' },
      { test: 'MCV', value: '87.5', unit: 'fL' },
    ],
    appointmentDate: '2024-01-17',
  },
  {
    id: 7,
    name: 'Sarah Johnson',
    username: '@sarah',
    sex: 'Female',
    age: 28,
    status: 'Waiting',
    email: 'sarah.johnson@mail.com',
    phone: '+8807FB001028',
    bp: '105/65',
    pulse: '72 bpm',
    weight: '60 Kg',
    lastChecked: 'Dr. Miller on 14 January 2024',
    prescription: '#201102020134',
    observation: 'Allergic rhinitis and sinusitis.',
    testsWithPrescriptions: [
      {
        test: 'Allergy Test',
        prescription: 'Tab.LORATADINE 10mg 1 + 0 + 0 × 15 Days',
      },
      {
        test: 'CBC',
        prescription: 'Cap.VITAMIN-C 500mg 1 + 0 + 0 × 30 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '7.5', unit: '1094/L' },
      { test: 'RBC', value: '4.3', unit: '1094/L' },
      { test: 'HGB', value: '13.2', unit: 'g/L' },
      { test: 'HCT', value: '39.0', unit: 'L/L' },
      { test: 'MCV', value: '90.5', unit: 'fL' },
    ],
    appointmentDate: '2024-01-18',
  },
  {
    id: 8,
    name: 'Michael Brown',
    username: '@michael',
    sex: 'Male',
    age: 52,
    status: 'Finished',
    email: 'michael.brown@mail.com',
    phone: '+8807FB001029',
    bp: '142/92',
    pulse: '80 bpm',
    weight: '85 Kg',
    lastChecked: 'Dr. Anderson on 11 January 2024',
    prescription: '#201102020135',
    observation: 'Hypertension follow-up visit.',
    testsWithPrescriptions: [
      {
        test: 'ECG',
        prescription: 'Tab.LOSARTAN 50mg 1 + 0 + 0 × 30 Days',
      },
      {
        test: 'Kidney Function',
        prescription: 'Tab.HYDROCHLOROTHIAZIDE 25mg 1 + 0 + 0 × 30 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '6.5', unit: '1094/L' },
      { test: 'RBC', value: '4.7', unit: '1094/L' },
      { test: 'HGB', value: '15.2', unit: 'g/L' },
      { test: 'HCT', value: '44.0', unit: 'L/L' },
      { test: 'MCV', value: '86.5', unit: 'fL' },
    ],
    appointmentDate: '2024-01-18',
  },
  {
    id: 9,
    name: 'Emma Wilson',
    username: '@emma',
    sex: 'Female',
    age: 31,
    status: 'Waiting',
    email: 'emma.wilson@mail.com',
    phone: '+8807FB001030',
    bp: '115/75',
    pulse: '68 bpm',
    weight: '59 Kg',
    lastChecked: 'Dr. Taylor on 13 January 2024',
    prescription: '#201102020136',
    observation: 'Migraine and tension headaches.',
    testsWithPrescriptions: [
      {
        test: 'CT Scan',
        prescription: 'Tab.SUMATRIPTAN 50mg 1 + 0 + 0 × 10 Days',
      },
      {
        test: 'Neurology',
        prescription: 'Cap.PROPRANOLOL 40mg 1 + 0 + 1 × 30 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '7.8', unit: '1094/L' },
      { test: 'RBC', value: '4.4', unit: '1094/L' },
      { test: 'HGB', value: '13.5', unit: 'g/L' },
      { test: 'HCT', value: '40.5', unit: 'L/L' },
      { test: 'MCV', value: '91.0', unit: 'fL' },
    ],
    appointmentDate: '2024-01-19',
  },
  {
    id: 10,
    name: 'David Lee',
    username: '@david',
    sex: 'Male',
    age: 47,
    status: 'Cancelled',
    email: 'david.lee@mail.com',
    phone: '+8807FB001031',
    bp: '128/84',
    pulse: '74 bpm',
    weight: '76 Kg',
    lastChecked: 'Dr. Harris on 09 January 2024',
    prescription: '#201102020137',
    observation: 'Post-operative knee surgery check.',
    testsWithPrescriptions: [
      {
        test: 'X-Ray',
        prescription: 'Tab.NAPROXEN 500mg 1 + 0 + 1 × 14 Days',
      },
      {
        test: 'Physical Therapy',
        prescription: 'Cap.GABAPENTIN 300mg 0 + 1 + 1 × 30 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '8.5', unit: '1094/L' },
      { test: 'RBC', value: '4.6', unit: '1094/L' },
      { test: 'HGB', value: '14.0', unit: 'g/L' },
      { test: 'HCT', value: '41.5', unit: 'L/L' },
      { test: 'MCV', value: '89.5', unit: 'fL' },
    ],
    appointmentDate: '2024-01-19',
  },
  {
    id: 11,
    name: 'Jennifer Martinez',
    username: '@jennifer',
    sex: 'Female',
    age: 34,
    status: 'Finished',
    email: 'jennifer.martinez@mail.com',
    phone: '+8807FB001032',
    bp: '112/74',
    pulse: '66 bpm',
    weight: '57 Kg',
    lastChecked: 'Dr. Clark on 16 January 2024',
    prescription: '#201102020138',
    observation: 'Annual health checkup - all normal.',
    testsWithPrescriptions: [
      {
        test: 'Mammogram',
        prescription: 'No medication required',
      },
      {
        test: 'Pap Smear',
        prescription: 'Follow-up in 1 year',
      },
    ],
    labResults: [
      { test: 'WBC', value: '6.9', unit: '1094/L' },
      { test: 'RBC', value: '4.2', unit: '1094/L' },
      { test: 'HGB', value: '13.0', unit: 'g/L' },
      { test: 'HCT', value: '38.5', unit: 'L/L' },
      { test: 'MCV', value: '91.5', unit: 'fL' },
    ],
    appointmentDate: '2024-01-20',
  },
  {
    id: 12,
    name: 'Robert Garcia',
    username: '@robert',
    sex: 'Male',
    age: 58,
    status: 'Waiting',
    email: 'robert.garcia@mail.com',
    phone: '+8807FB001033',
    bp: '138/86',
    pulse: '76 bpm',
    weight: '80 Kg',
    lastChecked: 'Dr. White on 17 January 2024',
    prescription: '#201102020139',
    observation: 'Asthma and breathing difficulties.',
    testsWithPrescriptions: [
      {
        test: 'Spirometry',
        prescription: 'Inh.SALBUTAMOL 2 puffs SOS',
      },
      {
        test: 'Chest X-Ray',
        prescription: 'Tab.MONTELUKAST 10mg 0 + 0 + 1 × 30 Days',
      },
    ],
    labResults: [
      { test: 'WBC', value: '8.8', unit: '1094/L' },
      { test: 'RBC', value: '5.0', unit: '1094/L' },
      { test: 'HGB', value: '15.5', unit: 'g/L' },
      { test: 'HCT', value: '46.0', unit: 'L/L' },
      { test: 'MCV', value: '87.0', unit: 'fL' },
    ],
    appointmentDate: '2024-01-20',
  },
];
